/**
 * Generated template module for upload schema
 * This file is auto-generated by scripts/generate-template.js
 * DO NOT EDIT MANUALLY
 */

export function getUploadSchemaTemplate(): string {
  return `import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';
import { randomUUID } from 'node:crypto';

// Re-export types from drizzle for convenience
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';

// Enums with typed values
export const imageStatusEnum = pgEnum('image_status', [
  'processing',
  'ready',
  'failed',
] as const);

export const assetVariantEnum = pgEnum('asset_variant', [
  'original',
  'thumb',
  'webp',
  'avif',
  'small',
  'medium',
  'large',
] as const);

// Export enum value types for type safety
export type ImageStatus = (typeof imageStatusEnum.enumValues)[number];
export type AssetVariant = (typeof assetVariantEnum.enumValues)[number];

// Images table
export const images = pgTable('images', {
  id: uuid('id')
    .primaryKey()
    .$defaultFn(() => randomUUID()),
  ownerId: uuid('owner_id'), // nullable for public uploads
  orgId: uuid('org_id'), // nullable for personal uploads
  entityType: varchar('entity_type', { length: 50 }), // e.g., 'appliance', 'recipe', 'user'
  entityId: uuid('entity_id'), // UUID of the associated entity
  filename: varchar('filename', { length: 255 }).notNull(),
  contentType: varchar('content_type', { length: 100 }).notNull(),
  byteSize: integer('byte_size').notNull(),
  status: imageStatusEnum('status').notNull().default('processing'),
  storageKey: varchar('storage_key', { length: 500 }).notNull(),
  publicUrl: text('public_url'), // nullable for private storage
  checksum: varchar('checksum', { length: 64 }), // SHA-256 hash
  alt: text('alt'), // accessibility text
  title: varchar('title', { length: 255 }),
  isPublic: boolean('is_public').notNull().default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

// Upload sessions for multipart uploads
export const uploadSessions = pgTable('upload_sessions', {
  id: uuid('id')
    .primaryKey()
    .$defaultFn(() => randomUUID()),
  imageId: uuid('image_id').references(() => images.id, {
    onDelete: 'cascade',
  }),
  uploadId: varchar('upload_id', { length: 255 }), // S3 multipart upload ID
  partCount: integer('part_count').notNull().default(1),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Asset variants for different sizes/formats
export const assetVariants = pgTable('asset_variants', {
  id: uuid('id')
    .primaryKey()
    .$defaultFn(() => randomUUID()),
  imageId: uuid('image_id')
    .notNull()
    .references(() => images.id, { onDelete: 'cascade' }),
  variant: assetVariantEnum('variant').notNull(),
  width: integer('width'),
  height: integer('height'),
  byteSize: integer('byte_size').notNull(),
  storageKey: varchar('storage_key', { length: 500 }).notNull(),
  publicUrl: text('public_url'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Image tags for organization
export const imageTags = pgTable('image_tags', {
  id: uuid('id')
    .primaryKey()
    .$defaultFn(() => randomUUID()),
  imageId: uuid('image_id')
    .notNull()
    .references(() => images.id, { onDelete: 'cascade' }),
  tag: varchar('tag', { length: 50 }).notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Improved type definitions using Drizzle's latest inference types
export type Image = InferSelectModel<typeof images>;
export type NewImage = InferInsertModel<typeof images>;
export type UploadSession = InferSelectModel<typeof uploadSessions>;
export type NewUploadSession = InferInsertModel<typeof uploadSessions>;
export type AssetVariantRecord = InferSelectModel<typeof assetVariants>;
export type NewAssetVariant = InferInsertModel<typeof assetVariants>;
export type ImageTag = InferSelectModel<typeof imageTags>;
export type NewImageTag = InferInsertModel<typeof imageTags>;

// Entity type helpers for better type safety
export type EntityType =
  | 'appliance'
  | 'recipe'
  | 'user'
  | 'ingredient'
  | 'equipment'
  | string;

// Utility types for common operations
export type ImageWithVariants = Image & {
  variants?: AssetVariantRecord[];
  tags?: ImageTag[];
};

export type ImageCreateInput = Omit<
  NewImage,
  'id' | 'createdAt' | 'updatedAt'
> & {
  variants?: Omit<NewAssetVariant, 'id' | 'imageId' | 'createdAt'>[];
  tags?: string[];
};

// Database relation helpers
export type ImageRelations = {
  variants: AssetVariantRecord[];
  tags: ImageTag[];
  uploadSession?: UploadSession;
};

// Export table names for migrations with proper typing
export const tableNames = {
  images: 'images',
  uploadSessions: 'upload_sessions',
  assetVariants: 'asset_variants',
  imageTags: 'image_tags',
} as const;

export type TableName = (typeof tableNames)[keyof typeof tableNames];

// Schema object for octoload core with enhanced typing
export const uploadSchema = {
  images,
  uploadSessions,
  assetVariants,
  imageTags,
  // Include enums for easier access
  imageStatusEnum,
  assetVariantEnum,
  // Include table names for convenience
  tableNames,
} as const;

// Schema type for type safety in core handlers
export type UploadSchema = typeof uploadSchema;

// Export commonly used query helpers
export type ImageQueries = {
  findById: (id: string) => Promise<Image | undefined>;
  findByStorageKey: (storageKey: string) => Promise<Image | undefined>;
  findByEntity: (entityType: string, entityId: string) => Promise<Image[]>;
  findWithVariants: (id: string) => Promise<ImageWithVariants | undefined>;
  create: (data: ImageCreateInput) => Promise<Image>;
  updateStatus: (id: string, status: ImageStatus) => Promise<void>;
  delete: (id: string) => Promise<void>;
};
`;
}
